# Generated by Django 5.2.17 on 2026-09-04 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('phone', models.CharField(help_text='شماره باید منحصر به فرد باشد.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تماس باید با فرمت صحیح وارد شود', regex='^09\\d{9}$')], verbose_name='شماره')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='نام مستعار')),
                ('is_active', models.BooleanField(default=True, help_text='مشخص میکند آیا کاربر فعال است یا نه')),
                ('is_staff', models.BooleanField(default=False, help_text='مشخص میکند آیا این کاربر میتواند وارد پنل ادمین شود یا نه')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربرها',
            },
        ),
    ]
